### PR TITLE
Update cloudfoundry cli

### PR DESCRIPTION
**Pull request by hairmare**
The version we are running is about a year old and I'm assuming this bump will fix some of the deploy problems we have been having lately.

### CODE REVIEW

**Comment by dhuf** [comment]
+1

**Comment by jrenggli** [comment]
+1
And thanks for your updates.

**Comment by hairmare** [comment]
@jrenggli This failed on circleci and is now failing on the docker hub. It fails while downloading slimerjs through npm and I can't reproduce this locally as it builds there without a hitch. Do you have any idea if you need slimerjs? I think it's part of sitespeed.io so I can either remove that or try updating node/npm to see if that helps.

**Comment by hairmare** [comment]
My issues are probably cdn related 😟 I'll rebuild until it works 😞

**Pull request merged**
